import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { UploadCloud, Loader2, RotateCcw, Download, FileDown, FileWarning } from 'lucide-react';
import clsx from 'clsx';
import type { ScanReport } from '../lib/scanner/types';
import type { WorkerRequest, WorkerResponse } from '../lib/scanner/worker';
import { type Locale, getUiStrings, formatBytes } from '../i18n';
import ReportView from './ReportView';

const MAX_BYTES = 100 * 1024 * 1024; // 100 MB
const WATCHDOG_MS = 90 * 1000; // 90s — terminate a stuck scan rather than leave the user stranded

// Same-origin demo files (public/demo/, generated by scripts/make_demo_pdfs.py)
// so "try an example" never leaves the browser either — it's a same-origin
// fetch, not an upload to anywhere. Labels are locale-specific (see
// src/i18n/ui.ts); fileName/url are shared across locales.
const DEMO_FILES = [
  {
    labelKey: 'resume' as const,
    fileName: 'resume-hidden-instructions.pdf',
    url: '/demo/resume-hidden-instructions.pdf',
  },
  {
    labelKey: 'hiddenLayer' as const,
    fileName: 'report-hidden-layer.pdf',
    url: '/demo/report-hidden-layer.pdf',
  },
];

// Carrying a report across the language switch.
//
// Switching language is a real navigation (/ ↔ /zh, two server-rendered pages),
// so the island remounts and a scan the visitor waited twenty seconds for is
// gone. The report is the only thing worth carrying over, and it travels
// through sessionStorage: same tab, same origin, never sent anywhere.
//
// The window it exists in is deliberately one page load wide. It is written
// only by a click on the language link — not when a scan finishes, not on any
// other navigation — and the page that reads it deletes it before rendering.
// A scan the visitor never switches languages on stores nothing at all. This
// is the one moment anything derived from a PDF is written to browser storage,
// and /privacy says so.
const HANDOFF_KEY = 'whatsinmypdf:lang-handoff';

function takeHandoff(): ScanReport | null {
  try {
    const raw = sessionStorage.getItem(HANDOFF_KEY);
    if (raw === null) return null;
    sessionStorage.removeItem(HANDOFF_KEY);
    const report = JSON.parse(raw) as ScanReport;
    // Anything half-written or hand-edited must land on the dropzone rather
    // than take the page down on the first property access.
    return typeof report?.fileName === 'string' && Array.isArray(report?.findings)
      ? report
      : null;
  } catch {
    // No sessionStorage (private mode, disabled storage) or unparseable value.
    return null;
  }
}

type State =
  | { phase: 'idle' }
  | { phase: 'loading'; fileName: string }
  | { phase: 'scanning'; fileName: string }
  | { phase: 'done'; report: ScanReport }
  | { phase: 'error'; message: string };

export default function Scanner({ locale = 'en' }: { locale?: Locale }) {
  const t = useMemo(() => getUiStrings(locale), [locale]);
  const DEMOS = useMemo(
    () => DEMO_FILES.map((d) => ({ ...d, label: t.scanner.demoLabels[d.labelKey] })),
    [t],
  );
  const [state, setState] = useState<State>({ phase: 'idle' });
  const [dragOver, setDragOver] = useState(false);
  const workerRef = useRef<Worker | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const watchdogRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const reportHeadingRef = useRef<HTMLHeadingElement>(null);
  const scanGen = useRef(0);

  const terminateWorker = useCallback(() => {
    if (watchdogRef.current !== null) {
      clearTimeout(watchdogRef.current);
      watchdogRef.current = null;
    }
    workerRef.current?.terminate();
    workerRef.current = null;
  }, []);

  useEffect(() => terminateWorker, [terminateWorker]);

  useEffect(() => {
    if (state.phase === 'done') reportHeadingRef.current?.focus();
  }, [state.phase]);

  // Restore on mount rather than in the useState initializer: this component is
  // server-rendered and then hydrated, so an initial state that differs between
  // the two is a hydration mismatch.
  useEffect(() => {
    const report = takeHandoff();
    if (report) setState({ phase: 'done', report });
  }, []);

  // The language link lives in the Astro-rendered header, outside this tree, so
  // the handoff is written from a document-level listener rather than an onClick.
  const stateRef = useRef(state);
  stateRef.current = state;
  useEffect(() => {
    const onClick = (e: MouseEvent) => {
      // A modified click opens a new tab. Chrome copies sessionStorage into
      // tabs opened that way, so writing here would plant the report in a tab
      // the visitor did not ask to see it in, and leave it behind in this one.
      if (e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
      if (!(e.target as Element | null)?.closest?.('[data-lang-switch]')) return;
      const cur = stateRef.current;
      if (cur.phase !== 'done') return;
      try {
        sessionStorage.setItem(HANDOFF_KEY, JSON.stringify(cur.report));
      } catch {
        // Storage blocked or full: the language switch still works, the
        // report is just not carried over.
      }
    };
    document.addEventListener('click', onClick, true);
    return () => document.removeEventListener('click', onClick, true);
  }, []);

  const scan = useCallback(
    async (file: File) => {
      const gen = ++scanGen.current;
      // Pre-checks before spinning up the worker or loading WASM.
      if (!(file.type === 'application/pdf' || file.name.toLowerCase().endsWith('.pdf'))) {
        setState({ phase: 'error', message: t.scanner.errors.notPdf });
        return;
      }
      if (file.size > MAX_BYTES) {
        setState({
          phase: 'error',
          message: t.scanner.errors.tooLarge(formatBytes(file.size)),
        });
        return;
      }
      if (file.size === 0) {
        setState({ phase: 'error', message: t.scanner.errors.empty });
        return;
      }

      setState({ phase: 'loading', fileName: file.name });
      let buffer: ArrayBuffer;
      try {
        buffer = await file.arrayBuffer();
      } catch {
        if (gen === scanGen.current) {
          setState({ phase: 'error', message: t.scanner.errors.readFailed });
        }
        return;
      }
      if (gen !== scanGen.current) return;

      terminateWorker();
      const worker = new Worker(new URL('../lib/scanner/worker.ts', import.meta.url), {
        type: 'module',
      });
      workerRef.current = worker;
      watchdogRef.current = setTimeout(() => {
        terminateWorker();
        setState({
          phase: 'error',
          message: t.scanner.errors.timedOut,
        });
      }, WATCHDOG_MS);

      worker.onmessage = (e: MessageEvent<WorkerResponse>) => {
        const msg = e.data;
        if (msg.type === 'progress') {
          setState({ phase: msg.stage, fileName: file.name });
        } else if (msg.type === 'done') {
          setState({ phase: 'done', report: msg.report });
          terminateWorker();
        } else {
          setState({ phase: 'error', message: msg.message });
          terminateWorker();
        }
      };
      worker.onerror = () => {
        setState({ phase: 'error', message: t.scanner.errors.failedToStart });
        terminateWorker();
      };

      const req: WorkerRequest = { buffer, fileName: file.name };
      worker.postMessage(req, [buffer]); // transfer the buffer, don't copy
    },
    [terminateWorker, t],
  );

  const onFiles = useCallback(
    (files: FileList | null) => {
      const file = files?.[0];
      if (file) void scan(file);
    },
    [scan],
  );

  // No internal busy guard here, matching onFiles: the trigger buttons are
  // `disabled={busy}` in the JSX below, so a disabled button never fires
  // this handler in the first place (same pattern as the file <input>).
  const loadDemo = useCallback(
    async (demo: (typeof DEMOS)[number]) => {
      const gen = ++scanGen.current;
      setState({ phase: 'loading', fileName: demo.fileName });
      let blob: Blob;
      try {
        const res = await fetch(demo.url);
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        blob = await res.blob();
      } catch {
        if (gen === scanGen.current) {
          setState({
            phase: 'error',
            message: t.scanner.errors.demoLoadFailed(demo.fileName),
          });
        }
        return;
      }
      if (gen !== scanGen.current) return; // superseded by a reset or another scan meanwhile
      const file = new File([blob], demo.fileName, { type: 'application/pdf' });
      void scan(file);
    },
    [scan, t],
  );

  const reset = useCallback(() => {
    scanGen.current++;
    terminateWorker();
    if (inputRef.current) inputRef.current.value = '';
    setState({ phase: 'idle' });
  }, [terminateWorker]);

  const downloadJson = useCallback((report: ScanReport) => {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const base = report.fileName.replace(/\.pdf$/i, '') || 'report';
    a.download = `${base}.whatsinmypdf-report.json`;
    a.click();
    URL.revokeObjectURL(url);
  }, []);

  const busy = state.phase === 'loading' || state.phase === 'scanning';

  // ---- Result / progress views ----
  if (state.phase === 'done') {
    return (
      <div className="mx-auto max-w-3xl space-y-6">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <p className="font-mono text-sm text-muted-foreground">
            {t.scanner.scannedLabel} <span className="text-foreground">{state.report.fileName}</span>
          </p>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={() => downloadJson(state.report)}
              className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-3.5 py-2 text-sm font-medium transition-colors hover:bg-muted focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"
            >
              <Download className="size-4" aria-hidden />
              {t.scanner.downloadJson}
            </button>
            <button
              type="button"
              onClick={reset}
              className="inline-flex items-center gap-2 rounded-lg bg-primary px-3.5 py-2 text-sm font-medium text-primary-foreground transition-opacity hover:opacity-90 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"
            >
              <RotateCcw className="size-4" aria-hidden />
              {t.scanner.scanAnother}
            </button>
          </div>
        </div>
        <ReportView report={state.report} headingRef={reportHeadingRef} locale={locale} />
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-2xl">
      <label
        htmlFor="pdf-input"
        onDragOver={(e) => {
          e.preventDefault();
          if (!busy) setDragOver(true);
        }}
        onDragLeave={() => setDragOver(false)}
        onDrop={(e) => {
          e.preventDefault();
          setDragOver(false);
          if (!busy) onFiles(e.dataTransfer.files);
        }}
        className={clsx(
          'group relative flex min-h-64 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed p-10 text-center transition-colors',
          dragOver ? 'border-primary bg-primary/5' : 'border-border bg-card hover:border-primary/60',
          'has-[:focus-visible]:border-primary has-[:focus-visible]:outline-2 has-[:focus-visible]:outline-offset-2 has-[:focus-visible]:outline-primary',
          busy && 'cursor-progress',
        )}
      >
        <input
          ref={inputRef}
          id="pdf-input"
          type="file"
          accept="application/pdf"
          className="sr-only"
          disabled={busy}
          onChange={(e) => onFiles(e.target.files)}
        />

        {busy ? (
          <>
            <Loader2 className="size-10 animate-spin text-primary" aria-hidden />
            <div role="status" aria-live="polite">
              <p className="mt-5 text-base font-medium">
                {state.phase === 'loading' ? t.scanner.loadingEngine : t.scanner.scanningForHiddenContent}
              </p>
              <p className="mt-1 font-mono text-sm text-muted-foreground">
                {'fileName' in state ? state.fileName : ''}
              </p>
            </div>
            <p className="mt-3 text-xs text-muted-foreground">{t.scanner.runsLocally}</p>
            <button
              type="button"
              onClick={(e) => {
                e.preventDefault();
                e.stopPropagation();
                reset();
              }}
              className="mt-4 text-sm font-medium text-primary underline underline-offset-2"
            >
              {t.scanner.cancel}
            </button>
          </>
        ) : (
          <>
            <span className="flex size-14 items-center justify-center rounded-full bg-muted text-primary transition-transform group-hover:scale-105">
              <UploadCloud className="size-7" aria-hidden />
            </span>
            <p className="mt-5 text-base font-medium">{t.scanner.dropTitle}</p>
            <p className="mt-1.5 text-sm text-muted-foreground">{t.scanner.dropSubtitle}</p>
          </>
        )}
      </label>

      <div className="mt-6">
        <p className="text-center text-sm text-muted-foreground">{t.scanner.tryExample}</p>
        <div className="mx-auto mt-3 flex max-w-md flex-col gap-2">
          {DEMOS.map((demo) => (
            <div
              key={demo.fileName}
              className="flex items-center justify-between gap-3 rounded-lg border border-border bg-card px-3.5 py-2"
            >
              <button
                type="button"
                disabled={busy}
                onClick={() => void loadDemo(demo)}
                className="truncate text-left text-sm font-medium text-primary underline-offset-2 hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary disabled:cursor-not-allowed disabled:text-muted-foreground"
              >
                {demo.label}
              </button>
              <a
                href={demo.url}
                download
                aria-disabled={busy}
                aria-label={t.scanner.demoDownloadAria(demo.label)}
                className={clsx(
                  'shrink-0 rounded p-1.5 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary',
                  busy && 'pointer-events-none opacity-50',
                )}
              >
                <FileDown className="size-4" aria-hidden />
              </a>
            </div>
          ))}
        </div>
      </div>

      {state.phase === 'error' && (
        <div
          role="alert"
          className="mt-5 flex items-start gap-3 rounded-xl border border-danger/40 bg-danger/10 p-4"
        >
          <FileWarning className="mt-0.5 size-5 shrink-0 text-danger" aria-hidden />
          <div className="space-y-2">
            <p className="text-sm leading-relaxed">{state.message}</p>
            <button
              type="button"
              onClick={reset}
              className="text-sm font-medium text-primary underline underline-offset-2"
            >
              {t.scanner.tryAnotherFile}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
